This is makeindex, version 2.15 [TeX Live 2016/W32TeX] (kpathsea + Thai support).
Scanning style file ./tabellequarto.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file tabellequarto.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (22 comparisons).
Generating output file tabellequarto.acr....done (18 lines written, 0 warnings).
Output written in tabellequarto.acr.
Transcript written in tabellequarto.alg.
